### ISSUE TITLE
[Proposal] Roadmap template

### ISSUE THREAD

**Issue by joshuamabina** [CodeTanzania/majifix-docs#4]
Hello,

While still in discussions at #2 - I felt to put something that could maybe trigger discussion around the format of the roadmap.

Please see gist to see my [proposal](https://gist.github.com/1b14fe81080382e68c4824e001576d5d.git).

The following are a few picks of inspiration:

- https://wiki.php.net/rfc/php7_57_roadmap
- https://wiki.diasporafoundation.org/Roadmap
- https://github.com/numpy/numpy/wiki/NumPy-Roadmap

**Comment by BenMaruchu** [comment]
@joshuamabina I like the template that you made. I think it looks perfect for our use.

Also we can look how this guys are doing it. [vscode team roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap)

**Comment by BenMaruchu** [comment]
@lykmapipo  @joshuamabina  created this [gist](https://gist.github.com/joshuamabina/1b14fe81080382e68c4824e001576d5d) you can take a look on it

**Comment by lykmapipo** [comment]
It seems [vscode](https://github.com/Microsoft/vscode) document much and have bigger community to lean from. Lets starts with them and produce what works for us. @joshuamabina & @BenMaruchu  Appreciated.

**Comment by joshuamabina** [comment]
@BenMaruchu & @lykmapipo thanks. Will review vscode roadmap and improve on what we have. Thanks.
